artifact_location: file:///Users/geethika/Desktop/Lead_Generation_Agent/Lead_Generation_Agent/mlflow/931850152383452133
creation_time: 1752396403184
experiment_id: '931850152383452133'
last_update_time: 1752396403184
lifecycle_stage: active
name: lead-generation-agent
