artifact_uri: file:///Users/geethika/Desktop/Lead_Generation_Agent/Lead_Generation_Agent/mlflow/931850152383452133/ffb05c26a8b64b8a949dbc82f703c74d/artifacts
end_time: 1752396562896
entry_point_name: ''
experiment_id: '931850152383452133'
lifecycle_stage: active
run_id: ffb05c26a8b64b8a949dbc82f703c74d
run_name: lead-generation-20250713-141739
source_name: ''
source_type: 4
source_version: ''
start_time: 1752396460387
status: 3
tags: []
user_id: geethika
