artifact_location: file:///Users/geethika/Desktop/Lead_Generation_Agent/Lead_Generation_Agent/mlflow/0
creation_time: 1752396403169
experiment_id: '0'
last_update_time: 1752396403169
lifecycle_stage: active
name: Default
