artifact_uri: file:///Users/geethika/Desktop/Lead_Generation_Agent/Lead_Generation_Agent/mlflow/931850152383452133/aeeb213a446a4597af1afc2fb3aba8c2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '931850152383452133'
lifecycle_stage: active
run_id: aeeb213a446a4597af1afc2fb3aba8c2
run_name: lead-generation-20250713-144115
source_name: ''
source_type: 4
source_version: ''
start_time: 1752397875615
status: 1
tags: []
user_id: geethika
